### ISSUE TITLE
[Feature Request] /mail

### ISSUE THREAD

**Issue by Soham52** [BasiqueEvangelist/pingspam#11]
/mail would be a command which would send a mail/message to a player who is offline.

The player to whom the mail was sent would see a notification whenever he would join the server.

The sub commands would be :
/Mail send <player> <message> - sends message to the player

/Mail read - would show all the mails which have not been deleted

/Mail delete <number> - would delete the mails in chronological order. for example - /mail delete 1 : would delete the oldest mail, /mail delete 2 would delete the last but one mail, and so on

/Mail clear - would delete all mails

/Mail block\ignore <player> - would block the blocked or ignored player from sending any more mails.

If a mail is sent to a player who is online, an error could be shown or it could still be sent and the other player can receive a notification.

**Comment by BasiqueEvangelist** [comment]
This feature seems out of scope for Pingspam. I'm considering making a different mod for this (codename: Pechkin). Perhaps I'll merge Pingspam and Pechkin later.

**Comment by Soham52** [comment]
That would nice also, thanks :)
