### ISSUE TITLE
Claimdata file not found exception crash

### ISSUE THREAD

**Issue by EvieTheOwl** [BasiqueEvangelist/pingspam#2]
**Version**: 1.1.0-pre3
**Server**: Crashing the TTT Adventure pack server
**Description**: Able to join the server for the first time successfully but on the 2nd attempt after restarting the server using `/stop` the file not found exception occurs. Can probably add in a try-catch loop for the file handler to make sure nothing crashes. 

**Crash report**: https://gist.github.com/profjb58/a54b02bcc4ef199ab8439cd65f49ae16

**Comment by BasiqueEvangelist** [comment]
Fixed in 0d418c550b9b64a88100d8c2818d77024265f450.
