### ISSUE TITLE
[Suggestion] Curseforge?

### ISSUE THREAD

**Issue by ghost** [BasiqueEvangelist/pingspam#8]
Hi,
This is a great mod!
Can I just suggest adding it to [Curseforge](https://curseforge.com) for the following reasons:
1. It is better as you can browse based on version or mod loader.
2. It has no adverts(ads are annoying!)
3. Curseforge is more popular so more people will see the mod.
4. Aternos does not accept mods from Modrinth yet.

**Comment by Oliver-makes-code** [comment]
> It has no adverts

It does though

**Comment by FoundationGames** [comment]
> It is better

no

> It has no adverts

no

Pretty sure that the mod is intentionally not on CurseForge
If you would like to improve Modrinth it is an open source project and you can view their GitHub page or join their community spaces.

**Comment by BasiqueEvangelist** [comment]
> Pretty sure that the mod is intentionally not on CurseForge

Not really. I didn't want to upload Pingspam to CurseForge before it was ready, but it seems everyone is fine with Pingspam as it is right now.

**Comment by BasiqueEvangelist** [comment]
https://www.curseforge.com/minecraft/mc-mods/pingspam/
