### ISSUE TITLE
Pinging players is case sensitive

### ISSUE THREAD

**Issue by CalXee** [BasiqueEvangelist/pingspam#9]
In every other vanilla command involving player names, you don't need to specify capital letters in the name and it will still work. However this is not the case with Pingspam, so it's a minor inconsistency/annoyance.

Installing the mod clientside alleviates this mostly, but not everybody has access to that luxury.

![2021-06-22_14 24 25](https://user-images.githubusercontent.com/68349758/122980078-430d4480-d366-11eb-854d-3682418a11f2.png)

**Comment by CalXee** [comment]
Btw I figured out how to get rid of the action bar (what I was referring to by "mentions"), don't worry.

**Comment by BasiqueEvangelist** [comment]
Fixed in `1.2.1`.
